### ISSUE TITLE
Can't read Tag from .mca, which is definitely not broken

### ISSUE THREAD

**Issue by yorrd** [Morlok8k/JNBT#5]
So I created a new world with Minecraft and I'm trying to load it. Every time I try to, this error is printed:

`java.io.IOException: [JNBT] TAG_End found without a TAG_Compound/TAG_List tag preceding it.`

The Code I'm testing with:

> NBTInputStream inputStream = new NBTInputStream(new FileInputStream(file), false);
> Tag tag = inputStream.readTag();

Is this library even up to date anymore? Or has it been abandoned like the other 1000  :D

**Comment by amorphine** [comment]
Same problem. Found no ways to fix...

**Comment by Morlok8k** [comment]
This is how i load the level.dat file in MLG: [link](https://github.com/Morlok8k/MinecraftLandGenerator/blob/master/src/morlok8k/MinecraftLandGenerator/SpawnPoint.java)

I've never used it on an actual .mca file, just "level.dat".

as for being up to date, the file format hasn't changed...  but this isn't really actively developed either.

If the TAG_End keeps being an issue, try editing [NBTInputStream.java](https://github.com/Morlok8k/JNBT/blob/master/src/org/jnbt/NBTInputStream.java) and remove the error and see what you get, like this:

```
				case NBTConstants.TYPE_END :
					return new EndTag();
```

**Comment by amorphine** [comment]
Thanks for reply. Unfortunately mca seems to be not very standart ntb to work with them with jbnt.
I fount https://github.com/LB--/MCModify. I hope that'll work

**Comment by Morlok8k** [comment]
if that works for you, then use it, but if you want to use JNBT, then all you should need to do is make the one edit i gave above.

NBT is NBT - there is nothing different other than version 19133 vs the older version 19132, and JNBT should support both.

**Comment by Morlok8k** [comment]
hmmm....  i've done some test on JNBT and mca files.  there are some issues, i'll look into it.

**Comment by SkyBeastMC** [comment]
Hey! Same here, please find a solution :(
I need to iterate alot of files to find the region which has the more tileentities to find a lost city in a world :) I can't do anything whithout it.

**Comment by amorphine** [comment]
MCA is not pure NBT-file, as far as I discovered. You can implement some code from here https://github.com/amorphine/SmartClean/blob/master/src/ager/MCAFile.java
I borrowed the code from somy guy I dont remember who exactly but you can look for the original source.

**Comment by MarkJeronimus** [comment]
MCA region files are not NBT files and as such I think they are technically not supported.

One easy fix to support them is adding more constructors to `NBTInputStream`/`NBTOutputStream` to handle raw streams (as with idcounts.dat) and streams prepended with a compression-type byte (each chunk stream in a region file).
